name = "MPITape"
uuid = "0eb6d5be-9499-4b92-a3d2-b4957f471b2b"
authors = ["Carsten Bauer <carsten.bauer@uni-paderborn.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
